### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by prinla** [aptly-io/grav-plugin-googlemaps#2]
Hello,
The developer-tools give me two errors related to this plugin:
"You have included the Google Maps API multiple times on this page. This may cause unexpected errors." 
& 
"Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required"
Could you help me how to solve this?

**Comment by aptly-io** [comment]
Hi
For the warning try remove the 'sensors=false' from googlemaps.php on line 94

For first error, don't know well,
- are you using the latest 1.0.10 grav?
- Can I access somehow your site to see what goes on? 

There's a new version in branch grav_v1_checkup on my github. Could you try that one? 

prinla notifications@github.com schreef op 3 maart 2016 14:58:28 CET:

> Hello,
> The developer-tools give me two errors related to this plugin:
> "You have included the Google Maps API multiple times on this page.
> This may cause unexpected errors." 
> & 
> "Google Maps API warning: SensorNotRequired
> https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required"
> Could you help me how to solve this?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/aptly-io/grav-plugin-googlemaps/issues/2

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by prinla** [comment]
Thanks for your help...
All problems resolved :+1:

**Comment by prinla** [comment]
Sorry I was a little bit to quick with my former post.
Indeed the "sensor"-problem is solved, but the multiple Api remains in version 0.2.2.
I tried to install the version 0.3.0. from your github, but could'nt get the plugin to run correctly.
With the same inputs as in my previous 0.2.2-version (meaning my .md-files being the same for the page), the map did not appear on my site. It seems to me as if the tagid couldn't be resolved by the plugin. Very strange. 
If you want access to the site please mail me: info@prinla.com ... the website is www.jakobs.lu
Thanks
Oliver

**Comment by aptly-io** [comment]
Hi
Oké I'll look into your site this weekend to check what might go wrong. I'll be checking jacobs.lu (that has the latest grav and the 0.3.x googlemaps plugin right? )
Kind regards
Francis

prinla notifications@github.com schreef op 4 maart 2016 16:07:29 CET:

> Sorry I was a little bit to quick with my former post.
> Indeed the "sensor"-problem is solved, but the multiple Api remains in
> version 0.2.2.
> I tried to install the version 0.3.0. from your github, but could'nt
> get the plugin to run correctly.
> With the same inputs as in my previous 0.2.2-version (meaning my
> .md-files being the same for the page), the map did not appear on my
> site. It seems to me as if the <tagid> couldn't be resolved by the
> plugin. Very strange. 
> If you want access to the site please mail me: info@prinla.com ... the
> website is www.jakobs.lu
> (and i have a second one running with the same problem of the multiple
> api with version 0.2.1 running -> www.tendancesjardins.lu)
> Thanks
> Oliver
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/aptly-io/grav-plugin-googlemaps/issues/2#issuecomment-192314993

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aptly-io** [comment]
@prinla Sorry to get back so late.
Maybe 0.3.5 addresses your problem.
A user narrowed down a conflict with the assets plug-in.
